name: test
on: push
jobs: 
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: gcc mandelbrotset.c -lm
      - run: sudo apt-get install gnuplot-nox
      - run: gnuplot gnuplot_projekt.gpi
      - run: ls
      - uses: actions/upload-artifact@v4
        with:
          path: gnuplot_projekt.pdf
